const allItems = [
  {
    name: "5 000 серебра",
    amount: 5000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "10 000 серебра",
    amount: 10000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "20 000 серебра",
    amount: 20000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "30 000 серебра",
    amount: 30000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "40 000 серебра",
    amount: 40000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "50 000 серебра",
    amount: 50000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "100 000 серебра",
    amount: 100000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "200 000 серебра",
    amount: 200000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "500 000 серебра",
    amount: 500000,
    wallet: "silver",
    image: "",
    type: "resource",
  },
  {
    name: "10 золота",
    amount: 10,
    wallet: "gold",
    image: "",
    type: "resource",
  },
  {
    name: "50 золота",
    amount: 50,
    wallet: "gold",
    image: "",
    type: "resource",
  },
  {
    name: "100 золота",
    amount: 100,
    wallet: "gold",
    image: "",
    type: "resource",
  },
  {
    name: "Super Conqueror",
    level: 10,
    amount: 7500,
    wallet: "gold",
    image:
      "https://thedailybounce.net/wp-content/uploads/2018/05/wot_banner_superconqueror_1920x900.jpg",
    type: "tank",
  },
  {
    name: "Dicker Max",
    level: 6,
    amount: 500,
    wallet: "gold",
    image: "https://i.ytimg.com/vi/yFFo0XXibSM/maxresdefault.jpg",
    type: "tank",
  },
  {
    name: "AMX 30B",
    level: 10,
    amount: 15000,
    wallet: "gold",
    image: "https://i.ytimg.com/vi/ZvPYcYE2hIM/maxresdefault.jpg",
    type: "tank",
  },
  {
    name: "E25",
    level: 7,
    amount: 1500,
    wallet: "gold",
    image: "https://i.ytimg.com/vi/JoB3Url4fcI/maxresdefault.jpg",
    type: "tank",
  },
  {
    name: "БТ-7 Артиллерийский",
    level: 3,
    amount: 100,
    wallet: "gold",
    image:
      "https://wiki.wgcdn.co/images/5/55/%D0%91%D0%A2-7_%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_art_1.jpg",
    type: "tank",
  },
  {
    name: "Type 59",
    level: 8,
    amount: 3500,
    wallet: "gold",
    image:
      "https://pic.rutubelist.ru/video/af/9d/af9d01f3ceb91856dc3479f76bed2cae.jpg",
    type: "tank",
  },
  {
    name: "50TP Prototyp",
    level: 9,
    amount: 7500,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "T 55A",
    level: 9,
    amount: 5000,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "AMX 30 1er prototype",
    level: 9,
    amount: 6000,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "Progetto 46",
    level: 8,
    amount: 5000,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "Action X",
    level: 8,
    amount: 4000,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "Pz V/IV",
    level: 5,
    amount: 950,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "T-127",
    level: 3,
    amount: 450,
    wallet: "gold",
    image: "",
    type: "tank",
  },
  {
    name: "T2 Light Tank",
    level: 2,
    amount: 250,
    wallet: "gold",
    image: "",
    type: "tank",
  },
];

export { allItems };
